"""Auto-generate a markdown tool reference from all TOOLS lists.

Run directly to print the reference:
    python -m handlers._schema_dump

Or call dump_markdown() to get the string programmatically.

This is the single source of truth for QA checklists and agent documentation.
Any time a tool schema changes, re-run this to regenerate the reference
rather than editing documentation by hand.
"""

from __future__ import annotations

import importlib
import json
import sys
from pathlib import Path

_HANDLER_MODULES = [
    "handlers.tools_search",
    "handlers.tools_storage",
    "handlers.tools_trajectory",
    "handlers.tools_skills",
    "handlers.tools_admin",
    "handlers.tools_cache",
]


def _prop_summary(props: dict, required: list[str]) -> list[str]:
    lines = []
    for name, spec in props.items():
        req_marker = " **(required)**" if name in required else ""
        ptype = spec.get("type", "")
        enum_vals = spec.get("enum")
        default = spec.get("default")
        description = spec.get("description", "")

        type_str = ptype
        if enum_vals is not None:
            type_str = "enum: `" + "`|`".join(str(v) for v in enum_vals) + "`"
        elif ptype == "array":
            items = spec.get("items", {})
            if "type" in items:
                type_str = f"array of {items['type']}"
            elif "oneOf" in items:
                types = "|".join(o.get("type", "?") for o in items["oneOf"])
                type_str = f"array of {types}"

        parts = [f"- `{name}`{req_marker} ({type_str})"]
        if description:
            parts.append(f"— {description}")
        if default is not None and default != "":
            parts.append(f"Default: `{json.dumps(default)}`.")

        lines.append(" ".join(parts))
    return lines


def dump_markdown(modules: list[str] | None = None) -> str:
    modules = modules or _HANDLER_MODULES
    sections: list[str] = [
        "# Archivist Tool Schema Reference",
        "",
        "> Auto-generated by `src/handlers/_schema_dump.py`. "
        "Do not edit manually — run `python -m handlers._schema_dump` to regenerate.",
        "",
    ]

    for mod_name in modules:
        mod = importlib.import_module(mod_name)
        tools = getattr(mod, "TOOLS", [])
        if not tools:
            continue

        # Section header derived from the module name
        group = mod_name.split(".")[-1].replace("tools_", "").replace("_", " ").title()
        sections.append(f"## {group} Tools")
        sections.append("")

        for tool in tools:
            sections.append(f"### `{tool.name}`")
            sections.append("")
            if tool.description:
                sections.append(tool.description.strip())
                sections.append("")

            schema = tool.inputSchema or {}
            props = schema.get("properties", {})
            required = schema.get("required", [])

            if props:
                sections.append("**Parameters:**")
                sections.append("")
                sections.extend(_prop_summary(props, required))
                sections.append("")
            else:
                sections.append("_No parameters._")
                sections.append("")

    return "\n".join(sections)


if __name__ == "__main__":
    src_dir = Path(__file__).resolve().parent.parent
    if str(src_dir) not in sys.path:
        sys.path.insert(0, str(src_dir))
    print(dump_markdown())
